"""Replay the REAL 2026-10-02 /compact wire payloads through the Claude runtime.

Why this file exists
--------------------
`tests/test_claude_commands.py` builds the compaction fixtures from the SDK's
own message parser, so it is safe from a shape the CLI never sends. This file
goes one step further: it carries the **verbatim** JSONL control frames captured
off a real `claude` CLI 2.1.284 / SDK 0.2.161 run, with nothing invented, and
pushes them through the real `ClaudeRuntime.execute_command("compact")` path.
If a future refactor reintroduces a hand-built fixture shape, the mismatch shows
up here first.

The frames matter because the SDK's `_internal/message_parser.py` parses every
non-task system message into

    SystemMessage(subtype=<str>, data=<the whole raw payload dict>)

so `status`, `compact_result` and `compactMetadata` are reachable only through
`.data`, never as attributes.

Captured payload source:
  /tmp/probe-compact-detail.py, CLI 2.1.284, sdk 0.2.161,
  session fd17cdec-ea63-4209-b810-954e732c9765.
"""

from __future__ import annotations

import asyncio
from types import SimpleNamespace
from typing import Any

import pytest
from claude_agent_sdk._internal.message_parser import parse_message

from connector.runtime_protocol import RuntimeConfig
from connector.runtimes.claude.runtime import ClaudeRuntime
from connector.runtimes.claude.timeline.markers import (
    claude_compact_event,
    is_local_command_echo,
)
from connector.runtimes.claude.timeline.messages import is_compact_summary_text
from test_claude_runtime import _RecordingHost

COMPACT_SESSION = "fd17cdec-ea63-4209-b810-954e732c9765"

# Verbatim CLI wire payloads (JSONL control frames) from the probe transcript.
WIRE_STATUS_COMPACTING = {
    "type": "system",
    "subtype": "status",
    "status": "compacting",
    "session_id": COMPACT_SESSION,
}

WIRE_STATUS_RESULT_SUCCESS = {
    "type": "system",
    "subtype": "status",
    "status": None,
    "compact_result": "success",
    "session_id": COMPACT_SESSION,
}

WIRE_COMPACT_BOUNDARY = {
    "type": "system",
    "subtype": "compact_boundary",
    "content": "Conversation compacted",
    "level": "info",
    "uuid": "db0784f0-8567-4625-bb8c-4020043ee630",
    "session_id": COMPACT_SESSION,
    "compactMetadata": {
        "trigger": "manual",
        "preTokens": 35134,
        "durationMs": 13997,
        "preservedSegment": {
            "headUuid": "644628e6-8c74-437d-b6ca-b38e8a31ff9f",
            "anchorUuid": "eea0bfd2-8d95-49a2-9fbe-92b2d5b5e695",
            "tailUuid": "91acfcb7-9ef9-4f17-ae4a-181096f0eb44",
        },
        "postTokens": 1865,
        "cumulativeDroppedTokens": 33269,
    },
}

WIRE_INIT = {"type": "system", "subtype": "init", "session_id": COMPACT_SESSION}

WIRE_SUMMARY = {
    "type": "user",
    "message": {
        "role": "user",
        "content": (
            "This session is being continued from a previous conversation that ran "
            "out of context. The summary below covers the earlier portion of the "
            "conversation.\n\nSummary:\n1. Primary Request and Intent: ..."
        ),
    },
    "uuid": "sum-uuid",
    "session_id": COMPACT_SESSION,
}

WIRE_STDOUT = {
    "type": "user",
    "message": {
        "role": "user",
        "content": "<local-command-stdout>Compacted </local-command-stdout>",
    },
    "uuid": "stdout-uuid",
    "session_id": COMPACT_SESSION,
}

WIRE_CAVEAT = {
    "type": "user",
    "message": {
        "role": "user",
        "content": (
            "<local-command-caveat>Caveat: The messages below were generated by the "
            "user while running local commands. DO NOT respond to these messages or "
            "otherwise consider them in your response unless the user explicitly "
            "asks you to.</local-command-caveat>"
        ),
    },
    "isMeta": True,
    "uuid": "caveat-uuid",
    "session_id": COMPACT_SESSION,
}

WIRE_COMMAND_ECHO = {
    "type": "user",
    "message": {
        "role": "user",
        "content": (
            "<command-name>/compact</command-name>\n            "
            "<command-message>compact</command-message>\n            "
            "<command-args></command-args>"
        ),
    },
    "uuid": "cmdecho-uuid",
    "session_id": COMPACT_SESSION,
}


def _result(num_turns: int = 0, result: str = "") -> Any:
    """The real ResultMessage shape: num_turns=0 and an empty result string."""
    return parse_message(
        {
            "type": "result",
            "subtype": "success",
            "duration_ms": 14120,
            "duration_api_ms": 13997,
            "is_error": False,
            "num_turns": num_turns,
            "session_id": COMPACT_SESSION,
            "result": result,
            "total_cost_usd": 0.0,
        }
    )


def _assistant(text: str, uuid: str) -> Any:
    return parse_message(
        {
            "type": "assistant",
            "message": {
                "id": f"msg-{uuid}",
                "role": "assistant",
                "model": "deepseek-v4.1-flash",
                "stop_reason": "end_turn",
                "content": [{"type": "text", "text": text}],
            },
            "uuid": uuid,
            "session_id": COMPACT_SESSION,
        }
    )


class _Client:
    def __init__(self, messages: list[Any]) -> None:
        self.messages = messages
        self.options: Any = None
        self.queries: list[str] = []

    async def connect(self) -> None:
        return None

    async def disconnect(self) -> None:
        return None

    async def query(self, prompt: Any) -> None:
        if not isinstance(prompt, str):
            first = [m async for m in prompt][0]
            prompt = first["message"]["content"]
        self.queries.append(prompt)

    async def receive_response(self) -> list[Any]:
        return self.messages

    def ensure_prompt_uuid(self) -> str:
        return "prompt-uuid"


class _Options:
    def __init__(self, **kwargs: Any) -> None:
        self.kwargs = kwargs


def _sdk() -> Any:
    return SimpleNamespace(
        __version__="1.0",
        ClaudeAgentOptions=_Options,
        PermissionResultAllow=SimpleNamespace,
        PermissionResultDeny=SimpleNamespace,
        list_sessions=lambda **_: [],
        get_session_info=lambda **_: None,
        get_session_messages=lambda **_: [],
    )


def _config() -> RuntimeConfig:
    return RuntimeConfig(runtime="claude", revision=1, values={"environment": {}})


async def _drive(
    messages: list[Any],
) -> tuple[_RecordingHost, _Client, ClaudeRuntime]:
    host = _RecordingHost()
    client = _Client(messages)

    def client_factory(sdk: Any, options: Any) -> _Client:
        _ = sdk
        client.options = options
        return client

    runtime = ClaudeRuntime(
        config=_config(),
        host=host,
        sdk_loader=_sdk,
        client_factory=client_factory,
    )
    result = await runtime.execute_command(
        session_id="sess_realwire",
        command="compact",
        external_session_id=COMPACT_SESSION,
    )
    assert result.ok is True
    task = runtime._sessions["sess_realwire"].active_task
    if task is not None:
        await task
    return host, client, runtime


def _markers(host: _RecordingHost) -> list[Any]:
    return [i for i in host.timeline_item_upserts if i.type == "marker"]


def _users(host: _RecordingHost) -> list[Any]:
    return [i for i in host.timeline_item_upserts if i.role == "user"]


# --------------------------------------------------------------------------
# 1. The SDK really does nest these fields (guards the premise of this file)
# --------------------------------------------------------------------------


def test_real_sdk_nests_compaction_fields_under_data() -> None:
    """Documents *why* a top-level-attribute fixture cannot see the real bug."""

    message = parse_message(WIRE_STATUS_COMPACTING)
    assert type(message).__name__ == "SystemMessage"
    # The parser puts the whole payload in `.data`; nothing is promoted out.
    assert message.data["status"] == "compacting"
    assert not hasattr(message, "status")
    assert not hasattr(message, "compact_metadata")
    assert not hasattr(message, "compactMetadata")

    boundary = parse_message(WIRE_COMPACT_BOUNDARY)
    assert boundary.data["compactMetadata"]["preTokens"] == 35134
    assert not hasattr(boundary, "compactMetadata")


# --------------------------------------------------------------------------
# 2. Every compaction signal the CLI emits is observed
# --------------------------------------------------------------------------


def test_real_wire_compacting_status_is_observed() -> None:
    """A real CLI `status: compacting` frame must open the running marker."""

    message = parse_message(WIRE_STATUS_COMPACTING)
    event = claude_compact_event(message)
    assert event is not None, (
        "a real CLI `status: compacting` frame must open the marker in the "
        "running state; it is dropped when the payload is read top-level only"
    )
    assert event.state == "started"


def test_real_wire_compact_result_is_observed() -> None:
    """A real CLI `compact_result: success` frame must close the marker."""

    message = parse_message(WIRE_STATUS_RESULT_SUCCESS)
    event = claude_compact_event(message)
    assert event is not None, (
        "a real CLI `compact_result: success` frame must close the marker; "
        "it is dropped when the payload is read top-level only"
    )
    assert event.state == "completed"
    assert dict(event.metadata)["compactResult"] == "success"


def test_real_wire_boundary_keeps_compact_metadata() -> None:
    """The boundary carries the token accounting and the native id."""

    event = claude_compact_event(parse_message(WIRE_COMPACT_BOUNDARY))
    assert event is not None
    assert event.state == "completed"
    metadata = dict(event.metadata)
    assert metadata.get("preTokens") == 35134
    assert metadata.get("cumulativeDroppedTokens") == 33269
    assert metadata.get("postTokens") == 1865
    assert metadata.get("durationMs") == 13997
    assert metadata.get("preservedSegment")["anchorUuid"] == (
        "eea0bfd2-8d95-49a2-9fbe-92b2d5b5e695"
    )
    assert event.native_message_id == "db0784f0-8567-4625-bb8c-4020043ee630"


# --------------------------------------------------------------------------
# 3. Full command replay through the real runtime
# --------------------------------------------------------------------------


def test_real_wire_command_replay_publishes_one_completed_marker() -> None:
    host, client, _ = asyncio.run(
        _drive(
            [
                parse_message(WIRE_STATUS_COMPACTING),
                parse_message(WIRE_INIT),
                parse_message(WIRE_COMPACT_BOUNDARY),
                parse_message(WIRE_SUMMARY),
                parse_message(WIRE_STDOUT),
                _result(),
            ]
        )
    )

    assert client.queries == ["/compact"], "the command must reach the CLI verbatim"
    assert _users(host) == [], "a command turn must never publish a user bubble"
    markers = _markers(host)
    # Dispatched, then the CLI's own start frame, then the boundary. All three
    # flip one item id instead of stacking three separators.
    assert [m.content["state"] for m in markers] == [
        "started",
        "started",
        "completed",
    ], "real wire should drive the running -> completed transition"
    assert markers[0].order_seq == markers[-1].order_seq, (
        "the marker must flip in place on one item id, not stack"
    )
    assert len({m.id for m in markers}) == 1
    assert markers[-1].content["preTokens"] == 35134
    assert markers[-1].content["trigger"] == "manual"


def test_real_wire_command_replay_always_leaves_a_verdict() -> None:
    """A command turn the CLI never acknowledges must still settle."""

    host, _, _ = asyncio.run(_drive([parse_message(WIRE_INIT), _result()]))

    markers = _markers(host)
    assert [m.content["state"] for m in markers] == ["started", "failed"]
    assert [m.status for m in markers] == ["running", "failed"]
    assert len({m.id for m in markers}) == 1


def test_real_wire_command_replay_suppresses_cli_chrome() -> None:
    host, _, _ = asyncio.run(
        _drive(
            [
                parse_message(WIRE_INIT),
                parse_message(WIRE_COMPACT_BOUNDARY),
                parse_message(WIRE_SUMMARY),
                parse_message(WIRE_CAVEAT),
                parse_message(WIRE_COMMAND_ECHO),
                parse_message(WIRE_STDOUT),
                _result(),
            ]
        )
    )

    assert _users(host) == []
    published = [
        str(i.content)
        for i in host.timeline_item_upserts
        if i.type != "marker"
    ]
    assert not any("local-command-stdout" in text for text in published)
    assert not any("This session is being continued" in text for text in published)
    assert not any("local-command-caveat" in text for text in published)
    assert not any("command-name" in text for text in published)


def test_real_wire_command_replay_returns_to_idle() -> None:
    host, _, _ = asyncio.run(
        _drive(
            [
                parse_message(WIRE_INIT),
                parse_message(WIRE_COMPACT_BOUNDARY),
                parse_message(WIRE_STDOUT),
                _result(),
            ]
        )
    )
    assert host.lifecycle_events[-1] == "state:idle"
    assert host.session_turn_ends[-1]["outcome"] == "completed"


def test_compact_summary_prefix_suppressed_on_real_user_message() -> None:
    from connector.runtimes.claude.timeline.messages import (
        is_synthetic_control_message,
    )

    assert is_compact_summary_text(
        WIRE_SUMMARY["message"]["content"]  # type: ignore[index]
    )
    assert is_synthetic_control_message(parse_message(WIRE_SUMMARY))


# --------------------------------------------------------------------------
# 4. order_seq: one allocator for messages and markers
# --------------------------------------------------------------------------


def test_mid_turn_compaction_does_not_collide_with_message_order_seq() -> None:
    """R4 measured a marker and an assistant reply sharing order_seq 3."""

    host = _RecordingHost()
    client = _Client(
        [
            _assistant("first reply", "a1"),
            parse_message(WIRE_STATUS_COMPACTING),
            parse_message(WIRE_COMPACT_BOUNDARY),
            _assistant("second reply", "a2"),
            _result(num_turns=1, result="second reply"),
        ]
    )

    def client_factory(sdk: Any, options: Any) -> _Client:
        _ = sdk
        client.options = options
        return client

    runtime = ClaudeRuntime(
        config=_config(),
        host=host,
        sdk_loader=_sdk,
        client_factory=client_factory,
    )

    async def _go() -> None:
        await runtime.start_turn(
            COMPACT_SESSION, COMPACT_SESSION, "hello", client_message_id="cm1"
        )
        task = runtime._sessions[COMPACT_SESSION].active_task
        if task is not None:
            await task

    asyncio.run(_go())

    # One item id may be upserted again as its state advances; two different
    # items may never claim the same slot.
    by_order: dict[int, set[str]] = {}
    for item in host.timeline_item_upserts:
        by_order.setdefault(item.order_seq, set()).add(item.id)

    duplicates = {seq: ids for seq, ids in by_order.items() if len(ids) > 1}
    assert not duplicates, f"order_seq collision between timeline items: {duplicates}"


@pytest.mark.parametrize(
    "wire",
    [WIRE_SUMMARY, WIRE_STDOUT, WIRE_CAVEAT, WIRE_COMMAND_ECHO],
)
def test_cli_chrome_never_reaches_the_model(wire: dict[str, Any]) -> None:
    """The CLI chrome frames must not be mistaken for the user's own prompt."""

    message = parse_message(wire)
    content = wire["message"]["content"]  # type: ignore[index]
    if content.startswith("<local-command-stdout>"):
        assert is_local_command_echo(message)
    else:
        assert content != "/compact"